version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: example      
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

  fastapi:
    restart: always
    build:
      context: .
    command: sh -c "sleep 10 && fastapi dev main.py --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"    
    depends_on:
      - db
